### ISSUE TITLE
Field Type Group not supported

### ISSUE THREAD

**Issue by leph83** [timothyjensen/acf-field-group-values#1]
If you put custom fields in a group, the values are not displayed. 
I found a solution for that according to your blog entry. 
I'm not happy with using 2 foreach loops, but was too lazy to find a better solution. And my php skills are also limited. 

elseif ( isset( $field['sub_fields'] ) && ($field['type'] !== 'group') ) {
...
} elseif ( $field['type'] === 'group')  {
            $new_config = $field['sub_fields'];
            $meta_key_group = [];

            foreach ( $new_config as &$field_config ) {
                $meta_key_group[] = $meta_key . "_" . $field_config['name'];
            }

            foreach ($meta_key_group as $key => $meta_key) {
                $results[ $meta_key ] = get_post_meta( $post_id, $meta_key, true );
            }
        }

**Comment by timothyjensen** [comment]
@leph83 Firstly, thank you for reporting the issues that you have encountered so far. 

As you can tell I've refactored the original function in favor of a class, which will be easier to maintain.  If you don't mind, please test the `develop` branch to see if the issues you mentioned are now resolved.  You can either install this repo as a plugin, or use it as a package within your theme.

**Comment by timothyjensen** [comment]
Closed by version 1.4.0
