### ISSUE TITLE
Add method for retrieving field labels

### ISSUE THREAD

**Issue by timothyjensen** [timothyjensen/acf-field-group-values#3]
It would be nice to optionally allow returning field labels in addition to their values. Each field value would need to be an array like so:
```php
<?php
// Current format.
'meta_key' => 'Field value';

// Optional format including field label.
'meta_key' => [
    'label' => 'Field label',
    'value' => 'Field value',
];
```

**Comment by stpha6** [comment]
Could you point me to where I could add the field labels? I'm loving this alternative to get_fields() - but would love to add in the labels.

**Comment by timothyjensen** [comment]
Hi @stpha6, thanks for your interest. It's actually not terribly complicated to include the labels. Here's a start:
https://github.com/timothyjensen/acf-field-group-values/commit/1c0d2d0aa51f5d5c4715e2dacae96b651988e89d#diff-b04a29abee52ec2e99bf17ccb30e0929788f9674d6792efd17eca13260a525e5R417-R420. I still need to add tests and a method for optionally enabling this feature, but you can try that change for now.
