### ISSUE TITLE
Now How to Loop Through Returned Flex Content Rows

### ISSUE THREAD

**Issue by brandonpence** [timothyjensen/acf-field-group-values#4]
I'm really looking forward to leveraging this! But I'm still not clear on now how to actually loop through the flexible content rows. This is my returned array:

```
Array
(
    [flex_row_test] => Array
        (
            [0] => Array
                (
                    [acf_fc_layout] => row_1
                    [test_1] => Fill it out.
                )

        )
)
```
Any help would be appreciated!

**Comment by timothyjensen** [comment]
Bill Erickson has a helpful post on this topic: https://www.billerickson.net/advanced-custom-fields-frontend-dependency#gist14350857.

For your specific situation you can do something like this:
```php
foreach ( $meta_data['flex_row_test'] as $row ) {
	switch ( $row['acf_fc_layout'] ) {
		case 'row_1':
			var_dump( $row['test_1'] );
			break;
		default:
			var_dump( 'none' );
	}
}
```

**Comment by timothyjensen** [comment]
I've closed out this ticket but feel free to reply if you have follow up questions.
