### ISSUE TITLE
Warning: As of version 2.0.0 the $config argument should include the field group key in addition to the array of fields.

### ISSUE THREAD

**Issue by senlin** [timothyjensen/acf-field-group-values#5]
This warning gets triggered, but no idea how to get the data to output instead of the warning.

My code is the exact same as [your sample](https://gist.github.com/timothyjensen/c8d8211effa8f098438700d828c21adb#file-acf-local-json-php), of course with my own group key.

Also, on a multilingual site with WPML, the json files are placed in language directories within the acf folder, so that is something that might need to be added to the code.

I can look into helping with that, but first I would need to get the output correctly :)

**Comment by timothyjensen** [comment]
Ah, that sample was intended for the old version of the plugin (pre-2.0).  In the [Usage section](https://github.com/timothyjensen/acf-field-group-values#usage) of the Readme step # 1 shows the proper format of the config. Basically, you need to pass `$config` into `get_all_custom_field_meta()` instead of `$config['field']`.

I'll update the Gist that you linked to with a comment that will clarify things, hopefully.

**Comment by timothyjensen** [comment]
As for the location of the JSON files, you probably just need to adjust the Local JSON path as described [here](https://www.advancedcustomfields.com/resources/local-json/).

**Comment by senlin** [comment]
Thanks for your reply!

Sorry, I should have read better, I came from [the article](https://www.timjensen.us/acf-get-field-alternative/) you posted on the topic. With the instructions in the usage section, things are now working. 

Something else: in [issue #4 ](https://github.com/timothyjensen/acf-field-group-values/issues/4) you refer to the article Bill Erickson did on the topic. Do you have any data available on how
 `get_all_custom_field_meta()` compares to the traditional `get_post_meta()`?

> As for the location of the JSON files, you probably just need to adjust the Local JSON path as described [here](https://www.advancedcustomfields.com/resources/local-json/).

Nah, that doesn't work. I think it is better to pass the language-code, like:

```
if ( 'en' == ICL_LANGUAGE_CODE ) {
	$field_group_json = 'group_xxx.json';
	$lang = 'en/';
} elseif ( 'de' == ICL_LANGUAGE_CODE ) {
	$field_group_json = 'group_yyy.json';
	$lang = 'de/';
} elseif ( 'es' == ICL_LANGUAGE_CODE ) {
	$field_group_json = 'group_zzz.json';
	$lang = 'es/';
}

$config = json_decode( file_get_contents( get_stylesheet_directory() . '/acf-json/' . $lang . $field_group_json ), true );
```

**Comment by timothyjensen** [comment]
> Do you have any data available on how
get_all_custom_field_meta() compares to the traditional get_post_meta()

Under the hood `get_all_custom_field_meta()` [uses native WP functions](https://github.com/timothyjensen/acf-field-group-values/blob/466dcb0c4fbda5659df48730ea8f7bedc056c675/src/Field_Group_Values.php#L158-L175) like `get_post_meta()`, so the only performance difference would be the amount of PHP processing. In simple use cases it would be slightly more performant to use the WP functions directly, but with more complex cases — such as when using ACF as a page builder — there will actually be _less_ processing with `get_all_custom_field_meta()`, and thus better performance.  The biggest performance gain is when you compare this method with ACF's `get_field()`, which adds loads of database hits and severely impacts performance.

> Nah, that doesn't work. I think it is better to pass the language-code

I admit I've never worked with WPML :). Thanks for offering a possible solution as it may help others who are working with WPML.

**Comment by senlin** [comment]
Thanks for elaborating on the performance. 

> Thanks for offering a possible solution as it may help others who are working with WPML.

This way is the manual way, it is also possible to output the language codes automatically. If you want, I can put something together for you? I could get this to you later this week. If you do, do you want me to open a new issue or just update this thread?

**Comment by timothyjensen** [comment]
That would be great, thanks.  I'll close out this issue, but please open another one for WPML once you have a solution that you're comfortable with sharing for others to use.

**Comment by senlin** [comment]
Actually, thought about it a bit more and since it will be necessary to manually add the json file names, the user might as well add the language-related parameters too as per my example above.
