### ISSUE TITLE
Some nested clone fields are not populated correctly

### ISSUE THREAD

**Issue by 75th** [timothyjensen/acf-field-group-values#7]
I have 

- A clone of a field group
    - containing a Flexible Content field
        - With layouts containing a clone of a field group
            - containing some fields. 

The fields inside that last level aren't getting populated. I'm still working on understanding the effects of the abomination I've constructed, but I think the problem is that the fields aren't getting their `meta_key_prefix`es set. Telling ACF to prefix the fields with the group name has no effect on the problem.

When I `print_r` the `$config` variable in `get_all_field_group_values`, several fields up the chain have their meta key prefixes set fine. But when it gets to the fields I describe above, the output looks like this:

```
Array
(
    [0] => Array
        (
            [key] => field_5b10590cbd1e2
            [label] => Title
            [name] => title
            [type] => text
            [instructions] => 
            [required] => 0
            [conditional_logic] => 0
            [wrapper] => Array
                (
                    [width] => 
                    [class] => 
                    [id] => 
                )

            [default_value] => 
            [placeholder] => 
            [prepend] => 
            [append] => 
            [maxlength] => 
            [meta_key_prefix] => 
        )

    [1] => Array
        (
            [key] => field_5b105973f792d
            [label] => Title Link
            [name] => title_link
            [type] => link
            [instructions] => 
            [required] => 0
            [conditional_logic] => 0
            [wrapper] => Array
                (
                    [width] => 
                    [class] => 
                    [id] => 
                )

            [return_format] => array
            [meta_key_prefix] => 
        )
)
```

Those two fields are definitely populated.

My tentative suspicion is that an up-to-date string of accumulated prefixes isn't getting passed around to the right functions; I notice that groups, repeaters, and flexible content fields pass along `$field_key` to their respective `get_*_field_values` handlers, but clone fields do not.

I'll continue working on this, but I'd love it if someone could fast-forward to the part where it gets fixed before I get there. :)

**Comment by timothyjensen** [comment]
What are you passing as the third argument to
`get_all_custom_field_meta()`.  It should be an array of all clone fields
that will be used, which in your case should be at least two clone field
groups.

Also, please post any PHP warnings or notices associated with the issue
you're experiencing as they should help narrow down the source of the
problem. I recommend using the plug-in Query Monitor to easily view PHP
errors (and a host of other really helpful features!).

Thanks,
Tim

**Comment by 75th** [comment]
I’m passing in an array of every field group on the site, except the main one. A bit later when I’m back at the computer I’ll confirm that I’m doing it right. And thanks for the plugin tip, I’m a Drupal refugee coming to grips with my new overlords

**Comment by timothyjensen** [comment]
I've been able to reproduce the error so it's definitely a bug in the code.  I will dig into it more and should have an update in a few days.  Would you be willing to test the bugfix when it's ready?

**Comment by 75th** [comment]
Absolutely!

**Comment by timothyjensen** [comment]
@75th Would you please test out the `develop` branch to see if that fixes the issue for you?
